/* Special defines for config.h.in to be generated by autoheader. */

/* Define if you want to use the GTK frontend. */
#undef GUI_GTK

/* Define if you want to use the text frontend. */
#undef GUI_TEXT

/* Define if you want to include SSL support. */
#undef USE_SSL
